### PR TITLE
Mexican Spanish translation

### PR DESCRIPTION
**Pull request by TheLegendofSaram**

### CODE REVIEW

**Comment by enjarai** [comment]
Isn't this just a copy of the english translation?

**Comment by TheLegendofSaram** [comment]
Dude

**Comment by TheLegendofSaram** [comment]
I forgot to ctrl + s the json file

**Comment by TheLegendofSaram** [comment]
Damn that hurts

**Comment by TheLegendofSaram** [comment]
Ill do it again

**Comment by TheLegendofSaram** [comment]
Okk, there it is

**Comment by enjarai** [comment]
Looks good 👍

**Pull request merged**
